### PR TITLE
Whiteboard

### PR DESCRIPTION
**Pull request by yjlo**
JIRA: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-255158
Feature Doc: https://confluence-eng-gpk2.cisco.com/conf/display/WTWC/Feature+Documentation

Added functions needed for whiteboard in-meeting
a) meetings-plugin
  -> meeting
      - startWhiteboardShare --> grant meeting floor request for specific whiteboard channel
      - stopWhiteboardShare --> release meeting floor request for specific whiteboard channel
      - setUpLocusMediaSharesListener --> edited handle whiteboard share status
  -> locusInfo
      - MediaSharesUtils --> Changed to have whiteboard in payload
  -> members
      - locusMediaSharesUpdate --> edited to handle whiteboard
b) board-plugin
  - authorizeMediaInjector --> needed for mobile client to receive transcoded whiteboard
  - unauthorizeMediaInjector --> clean up KMS authorizations made for sharing whiteboard
c) Updated Unit and Integration testing (please refer to feature doc for testing scenarios)
Reatime test failing JIRA -> https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284476

### CODE REVIEW

**Comment by marcin-bazyl** [comment]
overall looks good to me, great job with adding all the testing scenarios! I'll try to test it manually with the web app later today/tomorrow just to double check that all screen sharing scenarios are still working and then I'll tick the approval.

**Comment by taymoork2** [comment]
Board Tests
Unit:
image

Integration:
image

**Comment by taymoork2** [comment]
Meetings tests:
Failure is due to flakiness
image

**Review by taymoork2 — APPROVED** [review]
LGTM

**Pull request merged**
