### PR TITLE
feat(meetings): meeting specific sdk bundle for cdn

### PR DESCRIPTION
**Pull request by mkesavan13**
# COMPLETES [SPARK-415995](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-415995)

## This pull request addresses

One of the customer, BBVA, came up for help in reducing the SDK bundle size for CDN as their VMs were not able to handle a file size of 2MB.

## by making the following changes

This PR allows users to include meetings as a standalone SDK in both CDN and NPM. While we do this we also removed support of Room ID in meetings-only SDK to get rid of encryption plugin which was occupying so much space.

It is to note that, now the CDN bundle size for meetings-only SDK is reduced by 50%

- The Webex JS SDK is 2.24 MB
- The Meetings JS SDK is 1.13 MB

### Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [x] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by arun3528 — APPROVED** [review]

**Review by InteractiveTimmy — COMMENTED** [review]
Looks like this fully decouples a few of the plugins/packages from meetings. Is this as intended?

**Comment by arun3528** [comment]
yes @InteractiveTimmy the package is huge and as part of harmony we are decoupling conversations from meetings so yes we are decoupling it to make the CDN size small as well as have developers look at them as different entities 

we can have a call to go over it if you want to

**Comment by arun3528** [comment]
@mkesavan13  did confirm if there is any other usage of conversations and he confirmed its not getting used other then the fetchmeetinginfo  and that to for hydra which web client does not use

**Comment by InteractiveTimmy** [comment]
@marcin-bazyl , could you take a look at this and let us know if these changes could be damaging?

**Review by InteractiveTimmy — COMMENTED** [review]
Does this need to be amended to the `exports` of the `webex` `package.json` file?

**Review by InteractiveTimmy — APPROVED** [review]
LGTM! Pending passing tests for CI and an approval from @arun3528 .

**Pull request closed without merging**
