### PR TITLE
Fix/moveToLobby: block receiving reactions in lobby

### PR DESCRIPTION
**Pull request by mickelr**
# COMPLETES #< INSERT LINK TO ISSUE >
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-535566

## This pull request addresses

Still can receive reactions after moved into lobby

## by making the following changes

Unsubcribe relay event when moved into lobby

### Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by mkesavan13 — COMMENTED** [review]
The change seems good. But shouldn't we be trying to find out why LLM gets connected without the user getting admitted into the meeting instead of unsubscribing? Right now, it seems like the following is happening,
- LLM gets connected
- User Comes into Lobby and the connected LLM is disconnected
- User joins the meeting and the LLM gets connected again

It should simply be,
- User comes into Lobby and waits
- User joins the meeting and the LLM gets connected

Also, it will be good to add a Jira ticket for this

**Comment by mickelr** [comment]
> The change seems good. But shouldn't we be trying to find out why LLM gets connected without the user getting admitted into the meeting instead of unsubscribing? Right now, it seems like the following is happening,
> 
> * LLM gets connected
> * User Comes into Lobby and the connected LLM is disconnected
> * User joins the meeting and the LLM gets connected again
> 
> It should simply be,
> 
> * User comes into Lobby and waits
> * User joins the meeting and the LLM gets connected
> 
> Also, it will be good to add a Jira ticket for this

After fix, the things will be:
> * User comes into Lobby and waits
> * User joins the meeting and the LLM gets connected
> * User is moved to lobby by host and disconnected LLM
> * User is moved into meeting again by host  and the LLM gets connected again

**Comment by mkesavan13** [comment]
> After fix, the things will be:
> 
> * User comes into Lobby and waits
> * User joins the meeting and the LLM gets connected
> * User is moved into lobby by host and disconnected LLM
> * User is moved back to meeting again by host  and the LLM gets connected again

Makes sense. The updateLLMConnection method disconnects and reconnects the LLM every time it is called unless the meeting.isJoined is false. Is it the case here that once host moves the user back to lobby, their `meeting.isJoined()` returns false?

**Comment by mickelr** [comment]
That's right. The state will be "IDLE" in lobby

**Comment by mickelr** [comment]
> > After fix, the things will be:
> > 
> > * User comes into Lobby and waits
> > * User joins the meeting and the LLM gets connected
> > * User is moved into lobby by host and disconnected LLM
> > * User is moved back to meeting again by host  and the LLM gets connected again
> 
> Makes sense. The updateLLMConnection method disconnects and reconnects the LLM every time it is called unless the meeting.isJoined is false. Is it the case here that once host moves the user back to lobby, their `meeting.isJoined()` returns false?

That's right. The state will be "IDLE" in lobby

**Review by mkesavan13 — APPROVED** [review]

**Review by JudyZhuHz — APPROVED** [review]
Approved

**Pull request merged**
