### PR TITLE
feat(share): enable low resolution mode

### PR DESCRIPTION
**Pull request by robstax**
# Pull Request Template

## Description

Allows the resolution of a share to be set to 720p or 1080p. If sharing video, dropping resolution mitigates FPS loss and screen tearing.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Test Coverage

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* SDK Version
* Node/Browser Version
* NPM Version

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mwegman** [comment]
Is there a way to test this change?

**Comment by robstax** [comment]
as far as i can tell, there are no tests at all around media or this file? is that correct, @arun3528 @chrisadubois ?

**Comment by arun3528** [comment]
@mwegman we have integration and samples which tests this feature but not unit test. Is it ok to merge it now . Its blocking the GA release for wireless screen share. 

Will add unit test for this function in a different PR if thats ok !?

**Comment by robstax** [comment]
@mwegman added integration test cases

**Comment by adamweeks** [comment]
If you rebase on master, it should run the integration tests on firefox 71 which still work.

**Pull request merged**
