### PR TITLE
fix(samples): reorder and group the ui with similar features

### PR DESCRIPTION
**Pull request by rarajes2**
# COMPLETES #< [SPARK-481813](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-481813)>

## This pull request addresses

Meetings samples page had become a bit clumsy with the addition of new features like multi-stream, allowing to play with local media prior to joining a meeting.

## by making the following changes

Re-arrange the UI elements and make the UI/UX easy to navigate and reason

https://github.com/webex/webex-js-sdk/assets/131742425/32cf790c-767c-436f-9d4f-ca3524bef125

**New collapse all**

https://github.com/webex/webex-js-sdk/assets/131742425/fb8b6d3e-95db-408c-aa5d-d2816db63ef8

**Global expand and collapse buttons**

https://github.com/webex/webex-js-sdk/assets/131742425/90f2b37f-ed44-450c-b277-7e69286f3850

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by Neeraj-swarnkar — COMMENTED** [review]
For accordion suggestion,
We use font-awesome lib in samples, We can use some ICON for accordion from this library.
For CSS,
we use [water css ](https://watercss.kognise.dev/) for basic styling, we can check this.

**Review by karthikraji2020 — COMMENTED** [review]
i have a few suggestion listed below.
1. add accordion icon on each section.
2. add slight transition css property while toggling the section.
3. meeting controls section can be closed at initial state.

**Review by mkesavan13 — APPROVED** [review]
Looks good to me. Approving

**Comment by nataliadelmar** [comment]
image
The collapse all button is not clear to a regular user. 
I would add a static header on the top (persist through scrolling) and have a Expand all and Collapse all like in this image

**Comment by nataliadelmar** [comment]
I wonder if this would frustrate users for not being able to switch any meeting parameter while being no the meeting without needing to scroll up and down. 

I made [this PR](https://github.com/webex/webex-js-sdk/pull/3003) some months ago as innovation day that I never managed to open. There I kept the 2-columns but made them both independently scrollable.

Im not too worried about it. Both approaches have pros and cons. My approach had:
Pros: great for switching input in different sections
Cons: not great for first-time users who need to visualize

I would prioritize first-time experience and clarity over multitasking, so Id go for your approach for now :)

**Comment by rarajes2** [comment]
> image The collapse all button is not clear to a regular user. I would add a static header on the top (persist through scrolling) and have a Expand all and Collapse all like in this image

Thanks for the review @nataliadelmar. The reason to keep `Collapse all` on the right side and not at the top is to keep more space for the features to be shown. If we keep the `Collapse all` at the top, that space will be occupied all the time and on a smaller screen, it would be a bit difficult for a user to play around. I have added a title on the collapse all button though, maybe I can improve the styling to make it more visible.

What's your thought on this @sreenara, @mkesavan13

**Comment by sreenara** [comment]
> > image The collapse all button is not clear to a regular user. I would add a static header on the top (persist through scrolling) and have a Expand all and Collapse all like in this image
> 
> Thanks for the review @nataliadelmar. The reason to keep `Collapse all` on the right side and not at the top is to keep more space for the features to be shown. If we keep the `Collapse all` at the top, that space will be occupied all the time and on a smaller screen, it would be a bit difficult for a user to play around. I have added a title on the collapse all button though, maybe I can improve the styling to make it more visible.
> 
> What's your thought on this @sreenara, @mkesavan13

I think it's ok to keep it as a button on top @rarajes2 . We should also have text saying "Expand All/Collapse All"  so it's clear what the button does.
The problem with keeping it on the side is when we reduce the width of the window or open developer tools on the side, it overlaps with the rest of the icons. See the screenshot below.
image

**Review by sreenara — APPROVED** [review]

**Comment by nataliadelmar** [comment]
I like the new button with the text 'Collapse all' and 'Expand all'. It is a lot more clear now.

I would, however, not make this button a switch/toggle button. If you have 2 of the 7 sections open, you may want to have a button to Expand All, as well as a button to Collapse all. Both are equally valid actions at points like this. For this reason, I would have 2 separate buttons: 'Collapse All' and 'Expand All'

image
Additionally, I would add the icons that show what the actions would do.

**Comment by nataliadelmar** [comment]
One more small thing: this button has a primary style: it has a blue background making it standout a lot more than any other button in the ui. Primary styles should only be applied to Call To Actions: 'Next' button, or 'Submit' button, 'Accept cookies', etc... 'Collapse/Expand' buttons are not primary: we do not need the user to press them for him to continue his flow. Thus, I would use a secondary style: blue outline, transparent background and blue text

**Comment by rarajes2** [comment]
@nataliadelmar - Addressed both of the comments. Please verify

**Review by nataliadelmar — APPROVED** [review]

**Pull request merged**
