### PR TITLE
fix(plugin-meetings): added roap enabled flag in client call initiate…

### PR DESCRIPTION
**Pull request by Neeraj-swarnkar**
# COMPLETES # [SPARK-372959 ](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-372959)

## This pull request addresses

New event field is being added for client events
To indicate if ROAP is enabled in the call join flow 
Captured isRoapCallEnabled flag in client.call.initiated event
Added test for call.initiated event in spec file

< DESCRIBE YOUR CHANGES >

Added isRoapCallEnabled flag in client.call.initiated event
Screenshots below after testing - 

Screenshot 2022-10-18 at 12 50 59 PM

Unit test screenshot -

image
image

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by meta-dipanshu-sharma — APPROVED** [review]
LGTM.

**Review by mkesavan13 — APPROVED** [review]
Looks good

**Review by arun3528 — COMMENTED** [review]
looks good , add necessary tests for this

**Comment by Neeraj-swarnkar** [comment]
> looks good , add necessary tests for this

@arun3528, we don't have test present for CALL_INITIATED event inside #join test. I can only see for LOCUS_JOIN_RESPONSE event in this file packages/node_modules/@webex/plugin-meetings/test/unit/spec/meeting/index.js

**Comment by Neeraj-swarnkar** [comment]
> looks good , add necessary tests for this
Hi @arun3528, added the unit test for call.initiated event in spec file. Screenshot Also attached. 
Please check. Thanks.

**Review by arun3528 — APPROVED** [review]

**Pull request merged**
