### PR TITLE
Remove mmmagic dep for file-type + update test-helpers

### PR DESCRIPTION
**Pull request by taymoork2**
Fixes libmagic dependency

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Comment by taymoork2** [comment]
Let me know if this commit needs to be split out

**Review by mwegman — APPROVED** [review]

**Review by lalli-flores — CHANGES_REQUESTED** [review]
Please place the `package.json` changes in a separate `fix` commit from the refactoring

**Comment by taymoork2** [comment]
not ready to be merged yet, testing on the web-client shows it doesnt work

**Comment by taymoork2** [comment]
After some triaging, it seems that the current implementation with mmmagic also returns null/undefined when looking up file-type information
So the fix is to not destructure and just check if the return value isn't undefined

**Review by mwegman — APPROVED** [review]

**Pull request merged**
