### PR TITLE
chore(deps): bumps tar to 6.2.1 version

### PR DESCRIPTION
**Pull request by RAM1232**
# COMPLETES #< https://github.com/webex/webex-js-sdk/security/dependabot/169 >

## This pull request addresses

This pull request address to upgrade the tar dependency to 6.2.1.

## by making the following changes

By changing the package.json and yarn.lock of geckodriver dependency to 4.4.2 the tar was upgraded to 6.2.1

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

After upgrading the dependencies we had tested through Meeting Sample App ,It was working fine for me.

- Initialization
- Registration
- Manage Meeting
- Streams
- Screen share
- Participants section 

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Comment by Parimala032** [comment]
Tested it out Working fine LGTM

**Review by mkesavan13 — CHANGES_REQUESTED** [review]
Screenshot 2024-07-26 at 4 15 06 PM

The `yarn why` says that tar is upgraded to 6.2.0 and the dependabot alert says the fix is available in 6.2.1. Please check

**Comment by RAM1232** [comment]
@mkesavan13, Initially, the file tree is in the format [attached screenshot below].The  three dependencies will not upgraded tar to non vunerable version,The another dependency geckodriver can be upgraded to latest version but the latest version not using tar as internal dependency.Now What we have to do to close this PR and dismiss that alert or Continue with the PR and merge this PR ?[
Screenshot 2024-07-26 172316
](url)

**Review by mkesavan13 — APPROVED** [review]
As discussed in the space, please mention in the Dependabot alert dismiss that this PR fixed whatever it could.

**Pull request merged**
