### PR TITLE
feat(samples): sample app provide option to select the resolution & UI adjustments

### PR DESCRIPTION
**Pull request by Neeraj-swarnkar**
# COMPLETES [#< SPARK-360345>](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-360345)

## This pull request addresses

Worked on Samples -
Added the height and width parameter to the remote screenShare layout - Removed
Some UI adjustment
Updating video element code for UI
show the current resolution and fps using the getSettings on the video track every 3 seconds

Screenshot 2022-09-15 at 8 01 55 PM
Screenshot 2022-09-15 at 8 01 19 PM
Screenshot 2022-09-15 at 8 00 55 PM

## by making the following changes

< DESCRIBE YOUR CHANGES >

Changes in samples code - 
docs/samples/browser-plugin-meetings/app.js
docs/samples/browser-plugin-meetings/index.html

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### Open Question

- [x] Check with Edonus team about the status of what they support for renderInfo inside changeVideoLayout method, they support video need to check if they suppot content (remoteShare).
- [x] Testing with valid values

### CODE REVIEW

**Comment by Neeraj-swarnkar** [comment]
Few Open Question,

Need to Check with Edonus team about the status of what they support for renderInfo inside changeVideoLayout method, they support video need to check if they suppot content (remoteShare).

Testing with valid values for remote Share

**Comment by Neeraj-swarnkar** [comment]
wiki for renderInfo : https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?spaceKey=WMQ&title=Render-info+protocol

It seems they support content. @arun3528

**Comment by arun3528** [comment]
@Neeraj-swarnkar  the UI looks good but if the functionality is not working  create a seperate ticket for it

**Comment by Neeraj-swarnkar** [comment]
> @Neeraj-swarnkar the UI looks good but if the functionality is not working create a seperate ticket for it

1. setRemoteVideoQuality is not triggering event media:ready
This didn't work in existing code also. https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/

2. remoteScreenShare not working properly, not reflecting in UI after change

We are looking into this.
@arun3528, @rajeshtezu90

**Comment by marcin-bazyl** [comment]
> 1. setRemoteVideoQuality is not triggering event media:ready
>    This didn't work in existing code also. https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/

Why should setRemoteVideoQuality() trigger event media:ready? I don't think it ever did and I don't see a reason why it should start to do it now. media:ready for remote* types is triggered when we start receiving a remote track and changing the quality of it doesn't cause us to receive a new track, it's still the same one

**Comment by arun3528** [comment]
we can just use the ready event to trigger the status but not use it as a indicator for remote quality change 

So use the media ready only to trigger the interval 

You will need to move it on top of the function

**Comment by Neeraj-swarnkar** [comment]
Most of the comments are incorporated, please re review. Thanks.
@arun3528, @rajeshtezu90

**Review by rajeshtezu90 — APPROVED** [review]
LGTM,
Since the remote screenshare layout change is not supported by API as of now, we may change the commit type as per the changes done in this PR.

**Review by arun3528 — APPROVED** [review]

**Pull request merged**
