### PR TITLE
fix(samples): video resolution issue fix

### PR DESCRIPTION
**Pull request by meta-dipanshu-sharma**
# COMPLETES #< [SPARK-389444](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-389444) >

## This pull request addresses

Resolution and frame rate of the video streams is not displayed correctly on samples when we join another meeting after leaving the first meeting.

**UPDATED REQUIREMENT**:

Also we need to separate local video and remote video resolution check interval because local video can be created without joining a meeting. And remote video resolution interval check should be cleared when we leave a meeting but local video resolution interval check should be when we stop the local video.

## by making the following changes
 Did split meetingsResolutionCheckInterval method in 2 d/f methods which are `localVideoResolutionCheckInterval` and `remoteVideoResolutionCheckInterval`. Former is called when we do `getMediaStreams()` and stopped when we stop local video while later is called after `addMedia()` and stopped when leave a meeting.

`meetingsResolutionCheckInterval()` is called during register. Changed it to be called on `addMedia()` function.

### Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by arun3528 — APPROVED** [review]

**Comment by meta-dipanshu-sharma** [comment]
> Approving, because this change is making things better, but it's not a full fix. We should also move the call to `clearMeetingsResolutionCheckInterval()` - right now it's done on the first "media:stopped" event which kind of works, but probably better to do it when we leave the meeting. Also the meetingsResolutionCheckInterval() kicks of an interval that gets settings for local and remote tracks - this should be separated because we can display the settings for local tracks even before we join the meeting and call addMedia()

1. Yes we should move `clearMeetingsResolutionCheckInterval()` after we call leaveMeeting() instead of media:stopped event. Will update the PR.

2. Yes, instead of calling `meetingsResolutionCheckInterval()` after addMedia(), we can move it to after we do `getMediaStreams()`. Now regarding separating `getLocalMediaSettings()` and `getRemoteMediaSettings()` we have 2 options here:
  2.1. Either we should not separate them because anyways we are checking if remoteVideoTrack exists or not before fetching 
         the settings for it so it will return directly without throwing an error.
  2.2 Or we can separate just it will be a slight complex logic then.  
  
What do you suggest? @marcin-bazyl @arun3528

**Comment by marcin-bazyl** [comment]
> > Approving, because this change is making things better, but it's not a full fix. We should also move the call to `clearMeetingsResolutionCheckInterval()` - right now it's done on the first "media:stopped" event which kind of works, but probably better to do it when we leave the meeting. Also the meetingsResolutionCheckInterval() kicks of an interval that gets settings for local and remote tracks - this should be separated because we can display the settings for local tracks even before we join the meeting and call addMedia()
> 
> 1. Yes we should move `clearMeetingsResolutionCheckInterval()` after we call leaveMeeting() instead of media:stopped event. Will update the PR.
> 2. Yes, instead of calling `meetingsResolutionCheckInterval()` after addMedia(), we can move it to after we do `getMediaStreams()`. Now regarding separating `getLocalMediaSettings()` and `getRemoteMediaSettings()` we have 2 options here:
>    2.1. Either we should not separate them because anyways we are checking if remoteVideoTrack exists or not before fetching the settings for it so it will return directly without throwing an error.
>    2.2 Or we can separate just it will be a slight complex logic then.
> 
> What do you suggest? @marcin-bazyl @arun3528

I think we should separate them, because they have different lifetime. The one for local video should start when we get the camera stream and stop when we stop the local camera stream - this can happen without even having any meeting. The remote video one is only valid after we call addMedia and should be stopped when we leave the meeting.

**Comment by meta-dipanshu-sharma** [comment]
> > > Approving, because this change is making things better, but it's not a full fix. We should also move the call to `clearMeetingsResolutionCheckInterval()` - right now it's done on the first "media:stopped" event which kind of works, but probably better to do it when we leave the meeting. Also the meetingsResolutionCheckInterval() kicks of an interval that gets settings for local and remote tracks - this should be separated because we can display the settings for local tracks even before we join the meeting and call addMedia()
> > 
> > 
> > 
> > 1. Yes we should move `clearMeetingsResolutionCheckInterval()` after we call leaveMeeting() instead of media:stopped event. Will update the PR.
> > 2. Yes, instead of calling `meetingsResolutionCheckInterval()` after addMedia(), we can move it to after we do `getMediaStreams()`. Now regarding separating `getLocalMediaSettings()` and `getRemoteMediaSettings()` we have 2 options here:
> >    2.1. Either we should not separate them because anyways we are checking if remoteVideoTrack exists or not before fetching the settings for it so it will return directly without throwing an error.
> >    2.2 Or we can separate just it will be a slight complex logic then.
> > 
> > What do you suggest? @marcin-bazyl @arun3528
> 
> I think we should separate them, because they have different lifetime. The one for local video should start when we get the camera stream and stop when we stop the local camera stream - this can happen without even having any meeting. The remote video one is only valid after we call addMedia and should be stopped when we leave the meeting.

Updated the code. Created 2 separate functions for local and remote video settings check. Called and stopped them at correct time as discussed above.

**Review by marcin-bazyl — APPROVED** [review]
Looks good, are you going to port this to the beta branch too?

**Comment by meta-dipanshu-sharma** [comment]
> Looks good, are you going to port this to the beta branch too?

Yes

**Pull request merged**
