### PR TITLE
fix(meetings): trigger ringing_stopped event for SIP bridge calls

### PR DESCRIPTION
**Pull request by arun3528**
Fixes issue with ringing stopped not triggering for sip bridge

### CODE REVIEW

**Review by lalli-flores — CHANGES_REQUESTED** [review]
Can you fix the commit message? seems like a character typo :)
```
fix(meetings): trigger ringing_stopped event for SIP bridge calls

**Review by lalli-flores — APPROVED** [review]

**Review by marcin-bazyl — APPROVED** [review]
There seems to be no unit tests for any of the "locus.participant_*" events in the existing SDK code... maybe this would be a good opportunity to add some?

**Comment by lalli-flores** [comment]
Good call out @marcin-bazyl 🎉

**Comment by arun3528** [comment]
thanks @marcin-bazyl  @lalli-flores  added the test for that

**Pull request merged**
