### PR TITLE
feat(plugin-meetings): add cpu info to MQA

### PR DESCRIPTION
**Pull request by edvujic**
# COMPLETES [WEBEX-379500](https://jira-eng-gpk2.cisco.com/jira/browse/WEBEX-379500)

## This pull request addresses

This pull request addresses the need to gather information about the user's CPU, specifically the number of logical processors available, to potentially populate the numberOfCores field in MQA. The numberOfCores is defined in the project's CpuInfo data model as found in the event dictionary.

While the exact mapping of logical processors to physical CPU cores can be complex, the `CpuInfo.getNumLogicalCores()` (from `@webex/web-capabilities`) provides a convenient way to determine the number of logical processor cores available for running threads on the user's computer. This PR proposes to utilize the `navigator.hardwareConcurrency` API to obtain the logical processor count and considers the implications of using this value as a proxy for the actual number of CPU cores.

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

### I certified that

- [X] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [X] I discussed changes with code owners prior to submitting this pull request

- [X] I have not skipped any automated checks
- [X] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by Shreyas281299 — APPROVED** [review]
Looks good to me.

**Review by Neeraj-swarnkar — APPROVED** [review]
Looks Good

**Review by marcin-bazyl — APPROVED** [review]

**Review by SomeBody16 — CHANGES_REQUESTED** [review]
left comments

**Comment by edvujic** [comment]
https://github.com/webex/webex-js-sdk/pull/3643

Closing as it will be handled by @antsukanova in the above mentioned PR.

**Pull request closed without merging**
