### PR TITLE
fix(deps): upgrading the dependencies to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by mkesavan13**
# COMPLETES [SPARK-359139](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-359139)

## This pull request addresses

It Contains all the dependabot PRs and manually raised PRs which are used to fix the npm audit on packages that have an security vulnerabilities issues

## by making the following changes
_"yarn. lock"_ and _"package. json"_ files

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [x] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

After Upgrading We tested the Sample App(Calling), It was working fine 

- Authentication
- Initialization
- Registration
- Call Initialization (outgoing call/incoming call)
- Call controls (hold/resume, mute/unmute)
- Call transfer (Blind transfer, Consult transfer)

After Upgrading We tested the Sample App(Meetings), It was working fine

- Initialization
- Registration
- Manage Meeting
- Streams   (local/remote)
- Screen share
- Participants section
- Advance Meetings control

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Comment by RAM1232** [comment]
@mkesavan13, We tested the Calling and Meeting Sample App with all the scenarios described in the PR description. It was LGTM for me.

**Review by Shreyas281299 — APPROVED** [review]

**Review by Kesari3008 — APPROVED** [review]

**Comment by Kesari3008** [comment]
@mkesavan13 I Just noticed this after approving that the amply url isn't working. Is it expected?

**Comment by Parimala032** [comment]
@Kesari3008  The amplify url was working fine when we tested everything with the calling sample app and meeting sample app but when the merging has happened it's not working it doesn't seem to happen. @mkesavan13 do you know the reason anything

**Comment by Shreyas281299** [comment]
I think since the branch is merged it won't work.

**Pull request merged**
