### PR TITLE
fix(env): update whistler service URL

### PR DESCRIPTION
**Pull request by AMANDUA**
# Pull Request Template

## Description

This PR comprises of code changes to fix whistler Service URL
https://sqbu-github.cisco.com/WebExSquared/configuration/commit/feac940a886c2f981744302a63fd8bda934918fd#diff-0d17b97cf1e30c007b9b6c556629d730

Fixes # (issue) https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-151293

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Test Coverage

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* SDK Version
* Node/Browser Version
* NPM Version

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AMANDUA** [comment]
@mwegman - can you merge this...thanks

**Comment by InteractiveTimmy** [comment]
Please update this against master so we can confirm if tests are passing appropriately.

**Comment by AMANDUA** [comment]
> Please update this against master so we can confirm if tests are passing appropriately.

@InteractiveTimmy  - tried rebased with master but integration test are still failing..doesn't seems due to my changes..can you have  a look...

**Comment by AMANDUA** [comment]
Screenshot_20200701-230222_Chrome

 @InteractiveTimmy / @adamweeks / @arun3528 / @mwegman / @chrisadubois  - seeing failure in `plugin-phone`, doesn't seems to be due to my changes, can someone help me with this?

**Comment by lalli-flores** [comment]
@AMANDUA, seems like updating the URL breaks all the phone plugin integration tests, as they rely on the Whistler service

**Comment by AMANDUA** [comment]
> @AMANDUA, seems like updating the URL breaks all the phone plugin integration tests, as they rely on the Whistler service

@lalli-flores - earlier i tried running test locally for `phone-plugin` without changes(i.e without whistler URL changes) there test were failing for `whistler endpoint` not found due to the changes https://sqbu-github.cisco.com/WebExSquared/configuration/commit/feac940a886c2f981744302a63fd8bda934918fd#diff-0d17b97cf1e30c007b9b6c556629d730.

i will have a look why after updating the `Whistler Endpoint` phone registration is getting failed

**Comment by AMANDUA** [comment]
@lalli-flores - checked the logs seems like the user is not getting created
image
seeing 400 , and the device is not getting registered with the flow

image

**Comment by lalli-flores** [comment]
@AMANDUA can you disable (e.g. skip) the integration tests for the `phone-plugin`? That is a plugin that we are planning on deprecating, so it should be ok to skip them.

**Comment by AMANDUA** [comment]
> @AMANDUA can you disable (e.g. skip) the integration tests for the `phone-plugin`? That is a plugin that we are planning on deprecating, so it should be ok to skip them.

Thanks @lalli-flores , i will `skip` the tests and will update my PR

**Comment by AMANDUA** [comment]
@lalli-flores - i updated the tests, and some flaky tests are failing, can you try re running the PR, or give me access to re run failed pr

**Comment by AMANDUA** [comment]
@lalli-flores - finally the build is now green...i didn't made any changes...just reran PR...
Ready for merge...

**Comment by lalli-flores** [comment]
> @lalli-flores - finally the build is now green...i didn't made any changes...just reran PR...
> Ready for merge...

Thanks for looking into it, though.I will get this through then 👍🏻

**Comment by lalli-flores** [comment]
@AMANDUA tests seem to be fine now, however, you need to update your branch with latest `master`. Seems like there might be conflicts to resolve

**Comment by lalli-flores** [comment]
One more thing, can you squash your commits into one and add `[skip ci]` at the end of message?
This type of change should not trigger a new release of the SDK

**Comment by AMANDUA** [comment]
Sure @lalli-flores , i will make the changes and will update my PR

**Comment by AMANDUA** [comment]
@lalli-flores - squashed all commits and updated the commit  message as well

**Pull request merged**
