### PR TITLE
feat: get status about whether raise hand is supported

### PR DESCRIPTION
**Pull request by shnaaz**
# COMPLETES #
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-348628

## This pull request addresses
Add method to get status about whether raise hand is supported in meeting / whether lower all hands is supported in meeting through SDK
Added tests

< DESCRIBE THE CONTEXT OF THE ISSUE >

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by maxinteger — APPROVED** [review]
Looks good

**Review by Coread — APPROVED** [review]

**Review by cscheffauer — APPROVED** [review]
LGTM!

**Comment by Coread** [comment]
possibly worth updating the docs in packages/node_modules/@webex/plugin-meetings/README.md

**Review by Coread — CHANGES_REQUESTED** [review]
Can you update the docs in packages/node_modules/@webex/plugin-meetings/README.md

**Review by Coread — APPROVED** [review]

**Pull request merged**
