### PR TITLE
Upstreamsvcs

### PR DESCRIPTION
**Pull request by chrisadubois**
# COMPLETES #< INSERT LINK TO ISSUE >

## This pull request addresses

Making energy forecast data an option for the WDM register and refresh calls

`all` doesn't change the current request, it is the default as we have today, we can use it to expand and request only certain parts from WDM from upstream services in the future.

https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?spaceKey=WBXT&title=Making+WDM+Upstream+Requests+optional+for+clients

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

manual and unit tests

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request
- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by Coread — APPROVED** [review]

**Comment by sreenara** [comment]
> all doesn't change the current request, it is the default as we have today, we can use it to expand and request only certain parts from WDM from upstream services in the future.

@chrisadubois the SDK doesn't send `IncludeUpstreamService` right now while doing WDM registration. Why are we adding this considering the link between WDM and U2C is going to be removed in the future. [Reference](https://sqbu-github.cisco.com/pages/WebExSquared/arch-docs/services/wdm/proposals/wep-0001.html)

**Review by sreenara — COMMENTED** [review]
Just one comment regarding the decision to add includeUpstreamServices

**Comment by chrisadubois** [comment]
@sreenara - that's actually exactly what this helps with for the future. upstream services are not limited to just the catalog. The default is `all`. Once the catalog is removed, that is fine, there are still settings, toggles, etc which are ALSO upstream services. In fact, we could build on this after this PR and remove the u2c reference right away via this query parameter and not include the catalog in the WDM response.

**Comment by chrisadubois** [comment]
@sreenara please also have a look at this wiki: https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?spaceKey=WBXT&title=Making+WDM+Upstream+Requests+optional+for+clients

**Review by sreenara — APPROVED** [review]

**Pull request merged**
