### PR TITLE
fix(plugin-meetings): Eliminate Unnecessary Camera Prompts for Disabled Video

### PR DESCRIPTION
**Pull request by Parimala032**
# COMPLETES #< [SPARK-539683](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-539683) >

## This pull request addresses

This pull request addresses the issue with a kitchen sink app as well as web client. When the user tries to disable the videoEnabled checkbox and sharVideoEnabled checkbox, it still asks for camera access. This pull request resolves this problem with the following changes:

## by making the following changes

Changes have been made in the plugin-meetings/meeting/src where previously getDevices() which is there in the handleDeviceLogging() function was being called without considering the user's usage. Now, getDevices is being called with parameters based on the user's requests.

https://github.com/user-attachments/assets/fce47477-c767-44fc-a005-2da7af2ebafa

### Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

Tested this Pull request by

1. uncheck the videoEnabled and shareVideoEnabled checkbox and click on joinWithMedia() button ----> ask for microphone permission
2. uncheck the audioEnabled and shareAudioEnabled checkbox and click on joinWithMedia() button -----> ask for camera permission
3. checked both checkboxes ----> ask for both permissions
4. unchecked for checkboxes -----> didn't ask  for neither of the permissions

### I certified that

- [ ] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [ ] I discussed changes with code owners prior to submitting this pull request

- [ ] I have not skipped any automated checks
- [ ] All existing and new tests passed
- [ ] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Comment by adhmenon** [comment]
Could we get a vidcast of the changes in the sample app? Would be useful for external reviewers as well.

**Comment by Parimala032** [comment]
> Could we get a vidcast of the changes in the sample app? Would be useful for external reviewers as well.

@adhmenon  added  please do re-review

**Review by Shreyas281299 — APPROVED** [review]
Changes looks good

**Review by adhmenon — APPROVED** [review]
LGTM. Thanks for adding the video.

**Pull request merged**
