### PR TITLE
chore(codeowners): update codeowners file

### PR DESCRIPTION
**Pull request by sreenara**
# COMPLETES # NA

## This pull request addresses

the issue of the Web SDK team not being added into reviews automatically as codeowners for packages where the Web Client and WCME teams are making changes.
The older CODEOWNERS file was fine because the teams were using different branches (`beta` and `master`). However, now that all teams are using the `next` branch, there is a need to be careful about breaking changes which can cause issues in applications consuming the SDK (Webex Web Client, Instant Connect, Widgets, 3rd party developer applications).

## by making the following changes

Update @webex/web-sdk as owner for `@webex/plugin-meetings`, `@webex/internal-plugin-voicea` and all their dependent packages as these are the main packages that the SDK team needs notifications on.

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [x] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

NA

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by mkesavan13 — CHANGES_REQUESTED** [review]
1. Since we are the calling owners, we can specify ourselves as Code Owners there
2. Considering that, we should also ensure if the packages that Calling depend on are also explicitly specified

Looks good otherwise

**Comment by sreenara** [comment]
> 1. Since we are the calling owners, we can specify ourselves as Code Owners there
> 2. Considering that, we should also ensure if the packages that Calling depend on are also explicitly specified
> 
> Looks good otherwise

We'd fall under the default rule of `*` since we are the Web SDK team right? The codeowners file says "Web SDK Team Ownership *". Calling comes under this, so it should be ok? If we create a separate rule for calling, then in the future we would have to create rules for all other plugins we are creating.

Calling only depends on `@webex/media-helpers` and that's added in the codeowners file.

**Comment by mkesavan13** [comment]
> > 1. Since we are the calling owners, we can specify ourselves as Code Owners there
> > 2. Considering that, we should also ensure if the packages that Calling depend on are also explicitly specified
> > 
> > Looks good otherwise
> 
> We'd fall under the default rule of `*` since we are the Web SDK team right? The codeowners file says "Web SDK Team Ownership *". Calling comes under this, so it should be ok? If we create a separate rule for calling, then in the future we would have to create rules for all other plugins we are creating.
> 
> Calling only depends on `@webex/media-helpers` and that's added in the codeowners file.

If we do not mention it specifically, it does ask for a review from us but, it doesn't ask for approval from our team and Calling needs approval from us for sure, right?

**Review by mkesavan13 — APPROVED** [review]

**Comment by sreenara** [comment]
> > > 1. Since we are the calling owners, we can specify ourselves as Code Owners there
> > > 2. Considering that, we should also ensure if the packages that Calling depend on are also explicitly specified
> > > 
> > > Looks good otherwise
> > 
> > 
> > We'd fall under the default rule of `*` since we are the Web SDK team right? The codeowners file says "Web SDK Team Ownership *". Calling comes under this, so it should be ok? If we create a separate rule for calling, then in the future we would have to create rules for all other plugins we are creating.
> > Calling only depends on `@webex/media-helpers` and that's added in the codeowners file.
> 
> If we do not mention it specifically, it does ask for a review from us but, it doesn't ask for approval from our team and Calling needs approval from us for sure, right?

Please see #3641 which requires a review and approval from the Web SDK team for calling change.

**Review by Kesari3008 — APPROVED** [review]

**Pull request merged**
