### PR TITLE
feat: add share video encoder implementation to share video mute event

### PR DESCRIPTION
**Pull request by brycetham**
# COMPLETES [SPARK-542195](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-542195)

## This pull request addresses

Being able to determine whether a hardware or a software encoder is being used when share video gets muted.

## by making the following changes

Including the share video encoder implementation in the SDK event that is emitted whenever the share video mute state changes.

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by edvujic — APPROVED** [review]

**Review by marcin-bazyl — APPROVED** [review]
Maybe it would have been better to have the `encoderImplementation` added as a more generic field in StatsAnalyzer that would be there for all outbound video not just specific to share, but approving anyway since only the share one is used right now

**Review by k-wasniowski — APPROVED** [review]

**Comment by brycetham** [comment]
> Maybe it would have been better to have the `encoderImplementation` added as a more generic field in StatsAnalyzer that would be there for all outbound video not just specific to share, but approving anyway since only the share one is used right now

Yeah, I think this would be a good enhancement for the future. I wasn't sure if it was possible for the encoder implementations to be different for different simulcast layers. https://datatracker.ietf.org/doc/html/rfc8853 kinda implies that it does ("the same video source encoded with different video-encoder types"), so I think it requires a bit more thought for main video. Decided to leave it out until we have a use case for it.

**Review by Kesari3008 — APPROVED** [review]
Would this change not require adjustment in test files as well

**Comment by brycetham** [comment]
> Would this change not require adjustment in test files as well

Ah yeah, thank. I'll add them. It's a small change so should be simple to test.

**Pull request merged**
