### PR TITLE
build: remove cspell and add them later

### PR DESCRIPTION
**Pull request by arun3528**
# Remove cspell and prettier   #< INSERT LINK TO ISSUE >

## This pull request addresses

Removed the cspell and will add it in the future PR with ES lint changes 
Adding this will change all the files so will be a very big PR 

## by making the following changes

< DESCRIBE YOUR CHANGES >

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [x] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested

< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by srinijay98 — APPROVED** [review]

**Review by mkesavan13 — CHANGES_REQUESTED** [review]
Looks good. Just one small change, can we remove cspell from the dependencies as well?

**Review by chburket — APPROVED** [review]
Are we supposed to commit install-state.gz?  Otherwise, looks good to me.

**Comment by Coread** [comment]
> Are we supposed to commit install-state.gz? Otherwise, looks good to me.
```
.yarn/install-state.gz is an optimization file that you shouldn't ever have to commit. It simply stores the exact state of your project so that the next commands can boot without having to resolve your workspaces all over again.
```
https://yarnpkg.com/getting-started/qa

**Review by Coread — CHANGES_REQUESTED** [review]
According to the docs install-state.gz should not be checked in

**Comment by arun3528** [comment]
@Coread  fixed the review comments

**Review by Coread — APPROVED** [review]

**Pull request merged**
