### PR TITLE
feat(plugin-meetings): start sending behavioral metrics to amplitude

### PR DESCRIPTION
**Pull request by arun3528**
# COMPLETES #[SPARK-302864](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302864)

## This pull request addresses

We are changing the current operational metrics to behaviors metrics so that we can track the user activity flow 
which help identifying the user flow and issues 

## by making the following changes

We are changing the metrics values from "Operational" to "behavioral" and adding some user properties like userID , os information etc 

### Change Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [x] Tooling change
- [ ] Internal code refactor

## The following scenarios where tested
https://analytics.amplitude.com/cisco-cross-project/dashboard/48b3zev
 Did manual test where the data is been shown in the dashboard 

### I certified that

- [x] I have read and followed [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request)
- [x] I discussed changes with code owners prior to submitting this pull request

- [x] I have not skipped any automated checks
- [x] All existing and new tests passed
- [x] I have updated the documentation accordingly

---

Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.

### CODE REVIEW

**Review by jonniespratley — APPROVED** [review]
👍

**Review by taymoork2 — APPROVED** [review]
LGTM

**Comment by arun3528** [comment]
Test are failing on screen which are flaky and has nothing to do with the current changes we have done for behavior metrics 
so merging the PR

**Comment by lalli-flores** [comment]
Known screen share sample tests are failing. Merging as they will be addressed separately

**Pull request merged**
